version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: badu_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - db
    networks:
      - appnet
      - proxy_network

  web:
    image: nginx:alpine
    container_name: badu_web
    restart: unless-stopped
    # Ports removed as they will be handled by Reverse Proxy
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    networks:
      - appnet
      - proxy_network

  db:
    image: mysql:8.0
    container_name: badu_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    # Database port remains internal to the network
    networks:
      - appnet

networks:
  appnet:
  proxy_network:
    external: true

volumes:
  dbdata:
